sudo: required

services:
  - docker

before_script:
  - docker --version

script:
  - docker build -t ericsage/orca:edge .
  - sed -i '/COPY \/repositories.*/d' Dockerfile
  - docker build -t ericsage/orca:stable .

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  skip_cleanup: true
  provider: script
  script: docker push ericsage/orca:edge && docker push ericsage/orca:stable
