sudo: required

services:
  - docker

script:
  - docker build -f Dockerfile.ubuntu -t ericsage/orca:ubuntu .
  - docker build -f Dockerfile.alpine -t  ericsage/orca:alpine-edge .
  - sed -i '/COPY \/repositories.*/d' Dockerfile
  - docker build -f Dockerfile.alpine -t ericsage/orca:alpine-stable .

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  skip_cleanup: true
  provider: script
  script: docker push ericsage/orca:ubuntu &&
          docker push ericsage/orca:alpine-edge &&
          docker push ericsage/orca:alpine-stable
